language: python
python:
  - "3.6"

install:
  - "pip install pipenv"
  - "pipenv install --dev --skip-lock"

script:
  - "pipenv run pytest --cov=app test/"

after_success:
  - "pipenv run coveralls"

branches:
  only:
   - master